import numpy as np
x=[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]
y=np.array(x)
z=np.zeros((3,2))
u=np.ones((3,2))
r=np.arange(3,10)
rs=np.arange(50).reshape(5,10)
ls=np.linspace(5,10,9)
a=[1,2,3,4,5]
a=np.array(a)
print(f'{ls}\n')
print(f'{rs}\n')
print(f'{r}\n')
print(f'{u}\n ')
print(z)
print(f'\n {y} ')
print(f'\n{a.max()} ')
print(f'\n{a.min()} ')
print(f'\n{a.argmax()} ')
print(f'\n{a.argmin()} ')
print(f'\n{a[2]} ')
k1=np.arange(10)
k2=np.arange(10,20)
print(f'\n {k1}')
print(f'\n {k2}')
print(k1+k2)
sin=np.sin(x)
log=np.log(x)
print(f'\n {sin}')
print(f'\n{np.full((3,3),True)} ')
print(f'\n {log}')