import numpy as np
import pandas as pd
x=[1,2,3,4,5]
y=['a','b','c','d','e']
k=pd.Series(data=y,index=x)
print(k)
k=pd.Series(y,x)
print(k)
k=pd.Series(x,y)
print(k)
A=[2,3,4,5]
B=[7,7,8,9]
C=[1,3,4,5]
D=[2,3,6,7]
E=[7,9,0,1]
df=pd.DataFrame([A,B,C,D,E],['a','b','c','d','e'],['x','y','w','k'])
print(df)
d={'a':[1,2,3,4,5],'b':[6,7,8,9,np.nan],'c':[1,2,3,np.nan,np.nan],'d':[6,7,np.nan,np.nan,np.nan],'e':[1,np.nan,np.nan,np.nan,np.nan]}
l=pd.DataFrame(d)
print('\n')
print(l.dropna(thresh=3))
print('\n')
print(l.dropna(thresh=2))
print('\n')
print(l.dropna(thresh=4))
print('\n')
print(l)
print(l['b'].fillna(value=l['b'].mean()))

a={'item':['apple','apple','orange','orange','guns','guns'],'days':['mon','tue','wed','thu','fri','sat'],'sales':[100,80,200,150,5,8]}
la=pd.DataFrame(a)
print(la)
x=la.groupby('item')
print(x.mean())
print('\n')
print(x.max())
print('\n')
print(x.describe())
print('\n')
print(x.describe().transpose())