import numpy as np 
import pandas as pd 
import matplotlib.pyplot  as plt 
import seaborn as sns 
df1=sns.load_dataset('tips')
df2=pd.read_csv('ece.csv')
x1=np.random.rand(10,5)
x2=np.random.rand(100,5)
df3=pd.DataFrame(x1,columns=['a','b','c','d','e'])
df4=pd.DataFrame(x2,columns=['a','b','c','d','e'])
#ax=df4.plot.kde(x='a',y='b')
#plt.show()
#ax=df4.plot.scatter(x='a',y='b')
#plt.show()
#ax=df4.plot.box(x='a',y='b')
#plt.show()
#cx=df4.plot.line()
#plt.show()
#cx=df4['a'].plot.line()
#plt.show()
#lx=df1.plot.kde()
#plt.show() 
#kx=df4.plot.hist()
#plt.show()
#fx=df4.hist()
#plt.show()
#fx=df3.plot.bar()
#plt.show()
#bx=df3.plot.area()
#plt.show()
#bx=df3.plot.area(alpha=0.5)
#plt.show()
#lx=df1.plot(kind='hist')
#plt.show()
lx=df1.plot(kind='bar')
plt.show()
